# Generated by Django 4.2.20 on 2025-04-13 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_module', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
