# Generated by Django 4.2.20 on 2025-04-21 15:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان محصول')),
                ('english_title', models.CharField(blank=True, help_text='برای استفاده در SEO و URLها', max_length=300, null=True, verbose_name='عنوان انگلیسی محصول')),
                ('sku', models.CharField(blank=True, help_text='کد انبارداری محصول (Stock Keeping Unit)', max_length=50, null=True, unique=True, verbose_name='کد SKU محصول')),
                ('price', models.PositiveIntegerField(help_text='قیمت به ریال', validators=[django.core.validators.MinValueValidator(10000)], verbose_name='قیمت اصلی')),
                ('discount_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='قیمت با تخفیف')),
                ('short_description', models.CharField(blank=True, max_length=360, null=True, verbose_name='توضیحات کوتاه')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات کامل محصول')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیرفعال')),
                ('is_featured', models.BooleanField(default=False, verbose_name='محصول ویژه')),
                ('is_bestseller', models.BooleanField(default=False, verbose_name='پرفروش')),
                ('is_new', models.BooleanField(default=False, verbose_name='محصول جدید')),
                ('is_delete', models.BooleanField(default=False, verbose_name='حذف شده/نشده')),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='تعداد موجودی')),
                ('low_stock_threshold', models.PositiveIntegerField(default=5, verbose_name='حداقل موجودی هشدار')),
                ('manage_stock', models.BooleanField(default=True, verbose_name='مدیریت موجودی')),
                ('backorder_allowed', models.BooleanField(default=False, verbose_name='مجاز به پیش\u200cخرید')),
                ('sold_individually', models.BooleanField(default=False, verbose_name='فروش تکی اجباری')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='وزن محصول به گرم', max_digits=6, null=True, verbose_name='وزن (گرم)')),
                ('internal_memory', models.IntegerField(null=True, verbose_name='حافظه داخلی')),
                ('selfie_camera', models.IntegerField(help_text='مگاپیکسل', null=True, verbose_name='دوربین سلفی ')),
                ('operating_system', models.CharField(max_length=48, null=True, verbose_name='سیستم عامل ')),
                ('finally_version', models.BooleanField(default=True, verbose_name='نسخه سیستم نهایی')),
                ('is_update_system', models.BooleanField(default=True, help_text='قابلیت اپدیت سیستم عامل', verbose_name='قابل ارتقاع به نسخه های بالاتر')),
                ('dimensions', models.CharField(blank=True, help_text='به صورت طول × عرض × ارتفاع', max_length=50, null=True, verbose_name='ابعاد محصول')),
                ('material', models.CharField(blank=True, max_length=100, null=True, verbose_name='جنس محصول')),
                ('memory_ram', models.IntegerField(null=True, verbose_name='حافظه RAM')),
                ('battery_life', models.IntegerField(null=True, verbose_name='میلی امپر ساعت')),
                ('sim_number', models.CharField(choices=[(' تک سیمکارت', 'SIM1'), ('دو سیمکارت', 'SIM2'), ('سه سیمکارت', 'SIM3')], max_length=20, null=True, verbose_name='ظرفیت سیمکارت ')),
                ('main_image', models.ImageField(upload_to='products/main/', verbose_name='تصویر اصلی محصول')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='products/thumbnails/', verbose_name='تصویر بندانگشتی')),
                ('url', models.SlugField(help_text='آدرس SEO-friendly برای محصول', max_length=300, unique=True, verbose_name='آدرس URL')),
                ('meta_title', models.CharField(blank=True, max_length=60, null=True, verbose_name='عنوان متا (SEO)')),
                ('meta_description', models.CharField(blank=True, max_length=160, null=True, verbose_name='توضیحات متا (SEO)')),
                ('meta_keywords', models.CharField(blank=True, max_length=200, null=True, verbose_name='کلمات کلیدی متا (SEO)')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ آخرین ویرایش')),
                ('publish_date', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ انتشار')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('pending', 'در انتظار بررسی'), ('published', 'منتشر شده'), ('archived', 'بایگانی شده')], default='draft', max_length=10, verbose_name='وضعیت محصول')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام ویژگی')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug ویژگی')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'ویژگی محصول',
                'verbose_name_plural': 'ویژگی\u200cهای محصولات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان دسته بندی')),
                ('url', models.SlugField(blank=True, help_text='این بخش به صورت خودکار از عنوان دسته\u200cبندی ایجاد می\u200cشود', verbose_name='آدرس URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیرفعال')),
                ('is_delete', models.BooleanField(default=False, verbose_name='حذف شده/نشده')),
                ('icon', models.CharField(blank=True, choices=[('fas fa-mobile-alt', 'موبایل'), ('fas fa-laptop', 'لپ\u200cتاپ'), ('fas fa-tablet-alt', 'تبلت'), ('fas fa-headphones', 'هدفون'), ('fas fa-keyboard', 'کیبورد'), ('fas fa-mouse', 'ماوس'), ('fas fa-desktop', 'کامپیوتر'), ('fas fa-print', 'پرینتر'), ('fas fa-server', 'سرور'), ('fas fa-hdd', 'هارد دیسک'), ('fas fa-memory', 'رم'), ('fas fa-microchip', 'پردازنده'), ('fas fa-tv', 'تلویزیون'), ('fas fa-refrigerator', 'یخچال'), ('fas fa-blender', 'مخلوط کن'), ('fas fa-fan', 'پنکه'), ('fas fa-oven', 'اجاق گاز'), ('fas fa-utensils', 'وسایل آشپزخانه'), ('fas fa-tshirt', 'لباس مردانه'), ('fas fa-female', 'لباس زنانه'), ('fas fa-child', 'لباس کودک'), ('fas fa-socks', 'جوراب'), ('fas fa-shoe-prints', 'کفش'), ('fas fa-mitten', 'دستکش'), ('fas fa-book', 'کتاب'), ('fas fa-book-open', 'مجله'), ('fas fa-pencil-alt', 'مداد'), ('fas fa-pen', 'خودکار'), ('fas fa-ruler', 'خط کش'), ('fas fa-calculator', 'ماشین حساب'), ('fas fa-dumbbell', 'ورزشی'), ('fas fa-basketball-ball', 'توپ بسکتبال'), ('fas fa-futbol', 'توپ فوتبال'), ('fas fa-bicycle', 'دوچرخه'), ('fas fa-swimming-pool', 'استخر'), ('fas fa-spa', 'زیبایی'), ('fas fa-pump-soap', 'شوینده'), ('fas fa-pills', 'دارو'), ('fas fa-first-aid-kit', 'کیت کمک\u200cهای اولیه'), ('fas fa-gamepad', 'بازی و سرگرمی'), ('fas fa-camera', 'دوربین'), ('fas fa-car', 'خودرو'), ('fas fa-baby-carriage', 'کودک'), ('fas fa-tools', 'ابزار'), ('fas fa-plug', 'لوازم برقی')], help_text='آیکون مناسب برای این دسته\u200cبندی را انتخاب کنید', max_length=50, null=True, verbose_name='آیکون')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_category/', verbose_name='تصویر دسته\u200cبندی')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات دسته\u200cبندی')),
                ('meta_title', models.CharField(blank=True, max_length=60, null=True, verbose_name='عنوان متا (SEO)')),
                ('meta_description', models.CharField(blank=True, max_length=160, null=True, verbose_name='توضیحات متا (SEO)')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ آخرین ویرایش')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='product_module.productcategory', verbose_name='دسته\u200cبندی والد')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی محصول',
                'verbose_name_plural': 'دسته\u200cبندی محصولات',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام رنگ')),
                ('hex_code', models.CharField(help_text='مثلاً #FFFFFF برای سفید', max_length=7, verbose_name='کد HEX رنگ')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیرفعال')),
            ],
            options={
                'verbose_name': 'رنگ محصول',
                'verbose_name_plural': 'رنگ\u200cهای محصولات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/images/', verbose_name='تصویر')),
                ('alt_text', models.CharField(blank=True, help_text='برای دسترسی\u200cپذیری و SEO', max_length=100, null=True, verbose_name='متن جایگزین (alt)')),
                ('is_main', models.BooleanField(default=False, verbose_name='تصویر اصلی')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product_module.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'تصویر محصول',
                'verbose_name_plural': 'تصاویر محصولات',
                'ordering': ['order'],
                'unique_together': {('product', 'is_main')},
            },
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='عنوان سایز')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='توضیحات سایز')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیرفعال')),
            ],
            options={
                'verbose_name': 'سایز محصول',
                'verbose_name_plural': 'سایزهای محصولات',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام مشخصه')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='product_module.productcategory', verbose_name='دسته\u200cبندی مربوطه')),
            ],
            options={
                'verbose_name': 'مشخصه فنی',
                'verbose_name_plural': 'مشخصات فنی',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='نام تگ')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug تگ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('products', models.ManyToManyField(blank=True, related_name='tags', to='product_module.product', verbose_name='محصولات')),
            ],
            options={
                'verbose_name': 'تگ محصول',
                'verbose_name_plural': 'تگ\u200cهای محصولات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='نام برند')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='product_brands/', verbose_name='لوگو برند')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات برند')),
                ('website', models.URLField(blank=True, null=True, verbose_name='وبسایت برند')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیرفعال')),
                ('meta_title', models.CharField(blank=True, max_length=60, null=True, verbose_name='عنوان متا (SEO)')),
                ('meta_description', models.CharField(blank=True, max_length=160, null=True, verbose_name='توضیحات متا (SEO)')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ آخرین ویرایش')),
            ],
            options={
                'verbose_name': 'برند محصول',
                'verbose_name_plural': 'برندهای محصولات',
                'ordering': ['title'],
                'indexes': [models.Index(fields=['title'], name='product_mod_title_490c1c_idx'), models.Index(fields=['is_active'], name='product_mod_is_acti_94174f_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=250, verbose_name='مقدار')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='product_module.productattribute', verbose_name='ویژگی')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='product_module.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'مقدار ویژگی محصول',
                'verbose_name_plural': 'مقادیر ویژگی\u200cهای محصولات',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='product_module.productbrand', verbose_name='برند محصول'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='product_module.productcategory', verbose_name='دسته\u200cبندی محصول'),
        ),
        migrations.AddField(
            model_name='product',
            name='favorited_by',
            field=models.ManyToManyField(related_name='products_they_favorited', to=settings.AUTH_USER_MODEL, verbose_name='کاربرانی که این محصول را پسندیدند'),
        ),
        migrations.AddField(
            model_name='product',
            name='related_products',
            field=models.ManyToManyField(blank=True, to='product_module.product', verbose_name='محصولات مرتبط'),
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.PositiveIntegerField(help_text='درصد تخفیف (1 تا 100)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='درصد تخفیف')),
                ('start_date', models.DateTimeField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateTimeField(verbose_name='تاریخ پایان')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='product_module.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'تخفیف',
                'verbose_name_plural': 'تخفیف\u200cها',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='کد SKU نوع محصول')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='قیمت (در صورت متفاوت بودن)')),
                ('discount_price', models.IntegerField(blank=True, null=True, verbose_name='قیمت با تخفیف')),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='تعداد موجودی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیرفعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_module.productcolor', verbose_name='رنگ')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_module.productimage', verbose_name='تصویر مرتبط')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='product_module.product', verbose_name='محصول پایه')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_module.productsize', verbose_name='سایز')),
            ],
            options={
                'verbose_name': 'نوع محصول',
                'verbose_name_plural': 'انواع محصولات',
                'ordering': ['product', 'color', 'size'],
                'unique_together': {('product', 'color', 'size')},
            },
        ),
        migrations.CreateModel(
            name='ProductSpecificationValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200, verbose_name='مقدار')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='product_module.product', verbose_name='محصول')),
                ('specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='product_module.productspecification', verbose_name='مشخصه فنی')),
            ],
            options={
                'verbose_name': 'مقدار مشخصه فنی',
                'verbose_name_plural': 'مقادیر مشخصات فنی',
                'unique_together': {('product', 'specification')},
            },
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام نظر دهنده')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل نظر دهنده')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='امتیاز (1-5)')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان نظر')),
                ('comment', models.TextField(verbose_name='متن نظر')),
                ('is_approved', models.BooleanField(default=False, verbose_name='تایید شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='product_module.product', verbose_name='محصول')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'نظر محصول',
                'verbose_name_plural': 'نظرات محصولات',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product'], name='product_mod_product_7eb6a7_idx'), models.Index(fields=['is_approved'], name='product_mod_is_appr_76a976_idx'), models.Index(fields=['rating'], name='product_mod_rating_1f3e76_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['url'], name='product_mod_url_8fd0a5_idx'),
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['is_active'], name='product_mod_is_acti_8feb27_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productattributevalue',
            unique_together={('product', 'attribute')},
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['url'], name='product_mod_url_d6d4dc_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sku'], name='product_mod_sku_d6c4ba_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['price'], name='product_mod_price_24ece9_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active'], name='product_mod_is_acti_1197d7_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_featured'], name='product_mod_is_feat_797fd7_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_bestseller'], name='product_mod_is_best_c9fa3d_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status'], name='product_mod_status_4ae4e0_idx'),
        ),
    ]
