# Generated by Django 4.2.19 on 2025-03-18 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('name', models.CharField(max_length=200, verbose_name='نام و نام کاربری')),
                ('email', models.EmailField(max_length=300, verbose_name='ایمیل')),
                ('message', models.TextField(verbose_name='متن پیغام')),
            ],
            options={
                'verbose_name_plural': 'لیست تماس با ما',
            },
        ),
    ]
