# Generated by Django 4.2.19 on 2025-03-18 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_module', '0002_contactus_is_read_by_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='data_request',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ثبت'),
        ),
    ]
