# Generated by Django 4.2.19 on 2025-03-18 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_module', '0003_contactus_data_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='responce',
            field=models.TextField(blank=True, null=True, verbose_name='پاسخ ادمین'),
        ),
    ]
