# Generated by Django 4.2.19 on 2025-03-19 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_module', '0004_contactus_responce'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='name',
            new_name='full_name',
        ),
    ]
