# Generated by Django 4.2.19 on 2025-03-19 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_module', '0005_rename_name_contactus_full_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='title',
            new_name='subject',
        ),
    ]
