# Generated by Django 4.2.19 on 2025-03-21 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_module', '0006_rename_title_contactus_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='image',
            field=models.ImageField(null=True, upload_to='contact-us/images'),
        ),
    ]
