# Generated by Django 4.2.19 on 2025-03-28 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_module', '0008_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='contact-us/images'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(upload_to='create_profile/images'),
        ),
    ]
