# Generated by Django 4.2.20 on 2025-04-10 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_module', '0009_alter_contactus_image_alter_userprofile_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
