# Generated by Django 4.2.20 on 2025-04-03 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل ما')),
                ('phone', models.CharField(max_length=15, verbose_name='شماره تماس ما')),
                ('address', models.TextField(verbose_name='ادرس ما')),
                ('facebook', models.URLField(verbose_name='ادرس فیسبوک')),
                ('instagram', models.URLField(verbose_name='ادرس اینستاگرام')),
                ('twitter', models.URLField(verbose_name='ادرس توییتر')),
                ('youtube', models.URLField(verbose_name='ادرس چنل یوتیوب')),
                ('city', models.CharField(max_length=100, verbose_name='شهر')),
            ],
        ),
    ]
