# Generated by Django 4.2.20 on 2025-04-03 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutusmodel',
            name='is_active_view',
            field=models.BooleanField(default=True, verbose_name='نمایش جزیات تماس با ما'),
        ),
    ]
