# Generated by Django 4.2.20 on 2025-04-03 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_module', '0002_aboutusmodel_is_active_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutusmodel',
            name='text_about_us',
            field=models.TextField(blank=True, null=True, verbose_name='متن درباره ما'),
        ),
    ]
