# Generated by Django 4.2.20 on 2025-04-03 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_module', '0003_aboutusmodel_text_about_us'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutusmodel',
            options={'verbose_name': 'درباره ما', 'verbose_name_plural': 'درباره ما'},
        ),
        migrations.AlterField(
            model_name='aboutusmodel',
            name='facebook',
            field=models.URLField(blank=True, null=True, verbose_name='ادرس فیسبوک'),
        ),
        migrations.AlterField(
            model_name='aboutusmodel',
            name='instagram',
            field=models.URLField(blank=True, null=True, verbose_name='ادرس اینستاگرام'),
        ),
        migrations.AlterField(
            model_name='aboutusmodel',
            name='twitter',
            field=models.URLField(blank=True, null=True, verbose_name='ادرس توییتر'),
        ),
        migrations.AlterField(
            model_name='aboutusmodel',
            name='youtube',
            field=models.URLField(blank=True, null=True, verbose_name='ادرس چنل یوتیوب'),
        ),
    ]
