# Generated by Django 4.2.20 on 2025-04-03 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_module', '0004_alter_aboutusmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutusmodel',
            name='image_us',
            field=models.ImageField(blank=True, null=True, upload_to='about_us/images/', verbose_name='تصویر ما'),
        ),
    ]
