# Generated by Django 4.2.20 on 2025-04-03 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_module', '0005_aboutusmodel_image_us'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutusmodel',
            name='fax',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='فکس'),
        ),
    ]
