# Generated by Django 4.2.20 on 2025-04-03 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_module', '0006_aboutusmodel_fax'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutusmodel',
            old_name='fax',
            new_name='fax_phone',
        ),
    ]
