# Generated by Django 4.2.20 on 2025-04-03 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_module', '0007_rename_fax_aboutusmodel_fax_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutusmodel',
            old_name='fax_phone',
            new_name='fax',
        ),
    ]
