# Generated by Django 4.2.20 on 2025-04-03 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_module', '0008_rename_fax_phone_aboutusmodel_fax'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutusmodel',
            name='telegram',
            field=models.URLField(blank=True, null=True, verbose_name='ادرس تلگرام'),
        ),
    ]
