# Generated by Django 4.2.20 on 2025-04-03 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_module', '0009_aboutusmodel_telegram'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutusmodel',
            name='whatsapp',
            field=models.URLField(blank=True, null=True, verbose_name='ادرس واتساپ'),
        ),
    ]
