# Generated by Django 4.2.20 on 2025-04-10 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_module', '0010_aboutusmodel_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutusmodel',
            name='last_updated_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutusmodel',
            name='number_year_old',
            field=models.IntegerField(blank=True, null=True, verbose_name='سال تجربه'),
        ),
    ]
