# Generated by Django 4.2.20 on 2025-04-21 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SliderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='عنوان اسلایدر')),
                ('short_description', models.CharField(blank=True, max_length=50, null=True, verbose_name='توضیحات کوتاه اسلایدر')),
                ('image_slider', models.ImageField(upload_to='slider_images', verbose_name='تصویر اسلایدر')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='فعال/غیرفعال')),
            ],
            options={
                'verbose_name': 'اسلایدر صفحه',
                'verbose_name_plural': 'اسلایدر های صفحه',
            },
        ),
    ]
