# Generated by Django 4.2.20 on 2025-04-21 15:46

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='لطفاً یک ایمیل معتبر وارد کنید')], verbose_name='ایمیل کاربر')),
                ('email_active_code', models.CharField(blank=True, max_length=102, null=True, unique=True, verbose_name='کد فعالسازی حساب')),
                ('reset_code_expiration', models.DateTimeField(blank=True, null=True)),
                ('full_name', models.CharField(blank=True, max_length=100, verbose_name='نام کامل')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/', verbose_name='تصویر پروفایل')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='شماره تلفن')),
                ('is_verified_phone', models.BooleanField(default=False, verbose_name='تلفن تأیید شده')),
                ('account_suspension', models.BooleanField(default=False, help_text='درصورت فعال بودن کاربر نمیتواند به سایت دسترسی داشته باشد ', verbose_name='تعلیق کردن حساب کاربر')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AboutUsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fax', models.IntegerField(verbose_name='فکس')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل پشتیبانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='نمایش این جزییات')),
            ],
            options={
                'verbose_name': 'اطلاعات صفحه تماس با ما',
                'verbose_name_plural': 'اطلاعات صفحه تماس با ما',
            },
        ),
        migrations.CreateModel(
            name='ContactUsSupendedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='عنوان')),
                ('full_name', models.CharField(max_length=200, verbose_name='نام و نام کاربری')),
                ('email', models.EmailField(max_length=300, verbose_name='ایمیل')),
                ('message', models.TextField(verbose_name='متن پیغام')),
                ('is_read_by_admin', models.BooleanField(default=False, verbose_name='خوانده شده توسط ادمین')),
                ('data_request', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ثبت')),
                ('responce', models.TextField(blank=True, null=True, verbose_name='پاسخ ادمین')),
            ],
            options={
                'verbose_name_plural': 'لیست تماس با ما',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('birth_date', django_jalali.db.models.jDateField(blank=True, help_text='فرمت: YYYY-MM-DD', null=True, verbose_name='تاریخ تولد (شمسی)')),
                ('national_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='کد ملی')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پروفایل تکمیلی',
                'verbose_name_plural': 'پروفایل\u200cهای تکمیلی',
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
