# Generated by Django 4.2.20 on 2025-04-21 16:07

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['-id'], 'verbose_name': 'پروفایل کاربر', 'verbose_name_plural': 'پروفایل\u200cهای کاربران'},
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'مرد'), ('F', 'زن'), ('O', 'سایر')], max_length=1, null=True, verbose_name='جنسیت'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='شماره تلفن باید با 09 شروع شود', regex='^09[0-9]{9}$')], verbose_name='تلفن همراه'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='birth_date',
            field=django_jalali.db.models.jDateField(blank=True, help_text='فرمت: ۱۴۰۳-۰۱-۰۱', null=True, verbose_name='تاریخ تولد (شمسی)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='national_code',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='کد ملی باید ۱۰ رقم باشد', regex='^[0-9]{10}$')], verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
