# Generated by Django 4.2.20 on 2025-04-23 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "account_module",
            "0003_alter_userprofile_options_remove_userprofile_address_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="address",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="آدرس محل زندگی"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="city",
            field=models.CharField(
                blank=True, max_length=80, null=True, verbose_name="شهر سکونت"
            ),
        ),
    ]
