# Generated by Django 4.2.20 on 2025-04-24 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account_module", "0004_userprofile_address_userprofile_city"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="national_code",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="کد ملی"
            ),
        ),
    ]
