# Generated by Django 4.2.20 on 2025-04-24 15:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account_module", "0005_alter_userprofile_national_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="national_code",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="کد ملی باید ۱۰ رقم باشد", regex="^[0-9]{10}$"
                    )
                ],
                verbose_name="کد ملی",
            ),
        ),
    ]
