# Generated by Django 4.2.20 on 2025-04-24 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account_module", "0006_alter_userprofile_national_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="birth_date",
            field=models.DateField(blank=True, null=True, verbose_name="تاریخ تولد"),
        ),
    ]
